Document: vlc-plugin-vlsub
Title: Debian vlc-plugin-vlsub Manual
Author: <insert document author here>
Abstract: This manual describes what vlc-plugin-vlsub is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vlc-plugin-vlsub/vlc-plugin-vlsub.sgml.gz

Format: postscript
Files: /usr/share/doc/vlc-plugin-vlsub/vlc-plugin-vlsub.ps.gz

Format: text
Files: /usr/share/doc/vlc-plugin-vlsub/vlc-plugin-vlsub.text.gz

Format: HTML
Index: /usr/share/doc/vlc-plugin-vlsub/html/index.html
Files: /usr/share/doc/vlc-plugin-vlsub/html/*.html
